name: Run TG-FileStream Bot

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyngrok

      - name: Create .env
        run: |
          echo "API_ID=${{ secrets.API_ID }}" >> .env
          echo "API_HASH=${{ secrets.API_HASH }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "BIN_CHANNEL=${{ secrets.BIN_CHANNEL }}" >> .env
          echo "HOST=0.0.0.0" >> .env
          echo "PORT=8080" >> .env

      - name: Start Ngrok Tunnel
        run: |
          python - <<EOF
          from pyngrok import ngrok
          url = ngrok.connect(8080)
          with open(".env", "a") as f:
              f.write(f"PUBLIC_URL={url}\n")
          print("Public URL:", url)
          EOF

      - name: Run TG-FileStream Bot
        run: |
          python3 -m tgfs
